### ISSUE TITLE
NPM Install script is failing

### ISSUE THREAD

**Issue by jackbarham** [tinderjs/tinder-desktop#161]
I've tried several times to run `npm install` and I get the following error at the end of the install process:

```
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! tinder-desktop@0.1.0 postinstall: `bower install && cd desktop-app && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tinder-desktop@0.1.0 postinstall script 'bower install && cd desktop-app && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tinder-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && cd desktop-app && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tinder-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tinder-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jackbarham/Code/tinder-desktop/npm-debug.log
```

I've also removed the `node-modules` folder then `sudo npm install --unsafe-perm` and get the same error.

**Comment by mayeaux** [comment]
`bower install && cd desktop-app && npm install`

Here's the command that it's running
Can you try running `bower install` separately and see what you get?

**Comment by jackbarham** [comment]
It seems to have thrown back a permissions issue:

```
Error: EACCES: permission denied, open '/Users/jackbarham/.config/configstore/bower-github.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Configstore.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
```

I tried `sudo` first and which didn't work

**Comment by mayeaux** [comment]
Yeah something is up with your bower installation. Troubleshoot that, I haven't seen this personally myself before.

**Comment by jackbarham** [comment]
Think I might have fixed it...

**Comment by jackbarham** [comment]
If it helps anyone else, this fixed it for me: https://github.com/bower/bower/issues/2262#issuecomment-216015078

**Comment by mayeaux** [comment]
Yeah, if I revisit this project I'll consider revamping the install process, if you want to make it simpler feel free to and then submit a PR, up to you👍🏻

**Comment by jackbarham** [comment]
I'm more of a UI designer and would like to tidy it up more in-line with the native app. However, in the meantime how do you 'Superlike' and 'Undo'?

**Comment by mayeaux** [comment]
Undo: Backspace
Superlike: Shift right
Surprised it's not in the docs anywhere. Hm 🤔

**Comment by jackbarham** [comment]
Thanks, I did eventually find it in the code.

**Comment by mayeaux** [comment]
If you want to add some docs for instructions I'm happy to merge it 👍🏻
