### ISSUE TITLE
@Marooned-MB errors

### ISSUE THREAD

**Issue by SaturnusDJ** [tinderjs/tinder-desktop#175]
@Marooned-MB hey bro trying to run your version but getting errors. After downloading the repo and running "npm install && gulp run" this is the output:

> [22:14:53] Using gulpfile ~\Documents\TD\Marooned-MB\tinder-desktop\gulpfile.js
> [22:14:53] Starting 'compile:scripts'...
> [22:14:53] Starting 'compile:stylesheets'...
> [22:14:53] Starting 'compile:fonts'...
> [22:14:53] Finished 'compile:stylesheets' after 85 ms
> [22:14:53] Finished 'compile:fonts' after 91 ms
> [22:14:53] Finished 'compile:scripts' after 112 ms
> [22:14:53] Starting 'compile:all'...
> [22:14:53] Finished 'compile:all' after 33 μs
> [22:14:53] Starting 'run'...
> stdout:
> 
> stderr: [1212:0218/221454:INFO:CONSOLE(4)] "$ is not a function", source: file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/error_handler.js (4)
> 
> stderr: [1212:0218/221454:INFO:CONSOLE(7)] "TypeError: $ is not a function
>     at file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/tinder-desktop.js:44:5
>     at Object.e [as invoke] (file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/vendor/angular.min.js:40:19)
>     at file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/vendor/angular.min.js:41:390
>     at p (file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/vendor/angular.min.js:7:355)
>     at db (file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/vendor/angular.min.js:41:366)
>     at c (file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/vendor/angular.min.js:19:463)
>     at yc (file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/vendor/angular.min.js:20:274)
>     at de (file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/vendor/angular.min.js:19:83)
>     at file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/vendor/angular.min.js:299:474
>     at HTMLDocument.b (file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/vendor/angular.min.js:178:159)", source: file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/error_handler.js (7)
> 
> stderr: [1212:0218/221454:INFO:CONSOLE(9)] "TypeError: $ is not a function", source: file:///C:/Users//Documents/TD/Marooned-MB/tinder-desktop/desktop-app/js/error_handler.js (9)

**Comment by Marooned-MB** [comment]
Hey, thanks for the report. I'm away from my pc for a week or so, I'll check it soon.

**Comment by SaturnusDJ** [comment]
Great, take care.
When your repo is working for me I will fork it and apply my CSS and probably remove some general things that seem obsolete to me.
Or we can start a version together. My js skills are still zero though.
Would be nice to make this app 'Single Page Application' with working back buttons. (Open profile of match from convo and use back button to go back into convo. Show active tab, etc.)

**Comment by Marooned-MB** [comment]
Well, I have downloaded whole repo from scratch, did install and run.. no problems whatsoever,
I'm using node.js v6.9.4 - maybe this will help?

I'm not using Tinder anymore [ ;-) ] so development of this branch is frozen. Feel free to use my changes if you find them helpful.
